### ISSUE TITLE
cannot be generated from h2 with "tableNamePattern" parameter.

### ISSUE THREAD

**Issue by uk-taniyama** [domaframework/doma-codegen-plugin#133]
OK

```
domaCodeGen {
    // make an arbitrary named block
    dev {
        url = 'jdbc:h2:file:./work/db/db;MODE=MySQL'
	// tableNamePattern = 'm.*'
   }
}
```

NG:> [DOMAGEN0005] Cannot get any tables. Check parameters such as url, schemaName, tableNamePattern and so on.

```
domaCodeGen {
    // make an arbitrary named block
    dev {
        url = 'jdbc:h2:file:./work/db/db;MODE=MySQL'
	tableNamePattern = '^m.*'
   }
}
```

**Comment by uk-taniyama** [comment]
いろいろ試したところ、何かのタイミングで、カレントディレクトリが変わっているらしい。

PWD:~/.gradle/daemon/7.5.1

そのため、以下のように明示的に絶対パスを指定したら正しく動作しました。
注意事項として記載してくれるとありがたいです。

OK
```
 domaCodeGen {
    // make an arbitrary named block
    dev {
       url = "jdbc:h2:file:$projectDir/work/db/db;MODE=MySQL"
	tableNamePattern = '^m.*$'
   }
}

```

＃指定の有無で変わるのがよくわかりませんが。

**Comment by uk-taniyama** [comment]
ただし、自動生成されるテストコード中にも、フルパスで埋め込まれてしまいますね......

**Comment by nakamura-to** [comment]
I’m glad to hear the problem has been resolved.
But, I don't think this is a problem specific to doma-codegen-plugin.
